server:
  port: 0

spring:
  sql:
    init:
      mode: always

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/event-management
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true